version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"

  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    env_file: .env-local
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
